@startuml

skinparam stereotype {
    CBackgroundColor #AF5A50
    ABackgroundColor #7D966E
    IBackgroundColor #D7AA50
}

skinparam class {
	BackgroundColor #E1EAF1
	ArrowColor #00557C
	BorderColor #99BAD0
}

abstract class CommunicationProvider
class Message
class ForwardSending

CommunicationProvider --|> ForwardSending
Message --* ForwardSending

@enduml
