@startuml

skinparam stereotype {
    CBackgroundColor #AF5A50
    ABackgroundColor #7D966E
    IBackgroundColor #D7AA50
}

skinparam class {
	BackgroundColor #E1EAF1
	ArrowColor #00557C
	BorderColor #99BAD0
}

abstract class Nodes
abstract class WeightFunction

class GaussLegendre
class GaussLobatto

class Polynomial

class Quadrature

Nodes --|> GaussLegendre
Nodes --|> GaussLobatto

WeightFunction --|> Polynomial

GaussLegendre ..* Quadrature
GaussLobatto ..* Quadrature
Polynomial ..* Quadrature

@enduml
